#!/bin/bash

# Put your code here
# You may only use the following external programs: ls, echo, awk, cat, grep, sort, wc, bc
declare -A sum 
declare -A val
while read -r line; do
	weight=$(echo "$line" | awk '{print $NF}')
	key=$(awk -v w="$weight" '{gsub(w, ""); print $0}' <<< "$line")
	val["$key"]=$weight
done < input.txt

for f in submissions/*; do\
	total=0
	name=$(echo "$f" | awk -F '/' '{print $NF}')
	for i in "${!val[@]}"; do
		count=$(grep -oiE "${i//+/\\+}?(ed|er|ation|ing|is|s|d|r)?" "$f" | wc -l)
		total=$(echo "scale=1; $total + ($count * ${val[$i]})" | bc)
	done
	sum["$name"]=$total
done

for person in "${!sum[@]}"; do
	count="${sum[$person]}"
	f_count=$(echo "$count" | awk '{printf "%g", $0}')
	echo "$f_count $person"
done | sort -nr
